# Generated by Django 5.1.1 on 2024-10-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bhw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('civil_status', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('civil_status', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('civil_status', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_typeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.account_type')),
                ('bhw_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.bhw')),
                ('officials_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.personnel')),
                ('resident_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.residents')),
            ],
        ),
    ]
