# Generated by Django 5.1.1 on 2024-10-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0003_alter_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_name', models.CharField(max_length=255)),
                ('hs_requirements', models.CharField(max_length=255)),
                ('hs_proof', models.CharField(max_length=255)),
                ('hs_image', models.ImageField(null=True, upload_to='images/')),
                ('hs_date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
