# Generated by Django 5.1.1 on 2024-10-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0003_remove_accounts_bhw_id_remove_accounts_officials_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_typeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.account_type'),
        ),
        migrations.AlterField(
            model_name='residents',
            name='birthdate',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
