# Generated by Django 5.1.1 on 2024-10-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0004_alter_accounts_account_typeid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_description', models.CharField(max_length=255)),
                ('service_requirements', models.CharField(max_length=255)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
