# Generated by Django 5.1.1 on 2024-10-08 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0004_alter_accounts_account_typeid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_name', models.CharField(max_length=255)),
                ('hs_requirements', models.CharField(max_length=255)),
                ('hs_proof', models.CharField(max_length=255)),
                ('hs_image', models.ImageField(null=True, upload_to='images/')),
                ('hs_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('requirements', models.CharField(max_length=255)),
                ('service_description', models.TextField(null=True)),
                ('service_price', models.IntegerField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('officials_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.personnel')),
            ],
        ),
    ]
