# Generated by Django 5.1.1 on 2024-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0005_healthservice_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_price',
            field=models.IntegerField(null=True),
        ),
    ]
