# Generated by Django 5.1.1 on 2024-10-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0005_healthservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=255)),
                ('phonenum', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
                ('time', models.TimeField(max_length=255)),
            ],
        ),
    ]
