# Generated by Django 5.1.1 on 2024-10-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0006_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
