# Generated by Django 5.1.1 on 2024-10-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0007_alter_schedule_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='purok',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
