# Generated by Django 5.1.1 on 2024-10-14 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0008_schedule_purok'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bhwService',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.healthservice'),
        ),
    ]
