# Generated by Django 5.1.1 on 2024-11-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0011_alter_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('requirements', models.CharField(max_length=255)),
                ('service_description', models.TextField(null=True)),
                ('service_price', models.IntegerField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('officials_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.personnel')),
            ],
        ),
    ]
