# Generated by Django 5.1.1 on 2024-11-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0013_bhw_auth_user_personnel_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhw',
            name='birthdate',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='birthdate',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
