# Generated by Django 5.1.1 on 2024-11-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0014_alter_bhw_birthdate_alter_personnel_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='resident_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.residents'),
        ),
    ]
