# Generated by Django 5.1.1 on 2024-11-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0016_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbreaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbreak_name', models.CharField(max_length=100)),
                ('outbreak_type', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField(blank=True, null=True)),
                ('purok', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
