# Generated by Django 5.1.1 on 2024-11-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0016_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('total_price', models.IntegerField(null=True)),
                ('r_date', models.DateTimeField(null=True)),
                ('Resident_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.residents')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.services')),
            ],
        ),
    ]
