# Generated by Django 5.1.1 on 2024-11-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0018_outbreaks_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbreaks',
            old_name='user',
            new_name='auth_user',
        ),
    ]
