# Generated by Django 5.1.1 on 2024-11-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0019_rename_user_outbreaks_auth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbreaks',
            old_name='auth_user',
            new_name='user',
        ),
    ]
