# Generated by Django 5.1.1 on 2024-11-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0020_rename_auth_user_outbreaks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbreaks',
            name='purok',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
